
name: Test Run

on:
  workflow_dispatch:
    inputs:
      inp:

jobs:
  test-run:
    runs-on: ubuntu-latest
    env:
      inp : ${{ github.event.inputs.inp }}
    steps:
      - uses: actions/checkout@v2

      - name: Check Node Version
        run: |
          node -v
          npm --version
      
      - name: Main
        run: |
          cd src
          python3 main.py
          
          chmod a+x test.sh
          ./test.sh
          echo $?
      
      - name: After Success
        if: success()
        run: |
          echo Success

      - name: After Failure
        if: failure()
        run: |
          echo Failure
