
name: Test Run

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        default: false

jobs:
  test-run:
    runs-on: ubuntu-latest
    
    env:
      DESTROY: ${{ github.event.inputs.destroy }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Check Node Version
        run: |
          node -v
          npm --version
      
      - name: Main
        run: |
          echo destroy1 = "$INPUT_destroy"
          echo destroy2 = "$DESTROY"
          cd src
          #python3 main.py
          
          chmod a+x test.sh
          ./test.sh
          echo $?
      
      - name: After Success
        if: success()
        run: |
          echo Success

      - name: After Failure
        if: failure()
        run: |
          echo Failure
