
name: Test Run

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        default: false

jobs:
  test-run:
    runs-on: ubuntu-latest
    
    env:
      DESTROY: ${{ github.event.inputs.destroy }}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Main
        run: |
          echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          tsc --version
          cd src
          #python3 main.py
          
          chmod a+x test.sh
          ./test.sh ${{ true }}
          echo $?
      
      - name: After Success
        if: success()
        run: |
          echo Success

      - name: After Failure
        if: failure()
        run: |
          echo Failure
