
name: CI

on:
  workflow_dispatch:
    inputs:
      inp:

jobs:
  test-run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        shell: cmd
        env:
          TF_VAR_api_key: ${{ secrets.IBM_API_KEY }}
        run: |
          curl -o terraform.zip https://releases.hashicorp.com/terraform/1.3.1/terraform_1.3.1_windows_amd64.zip
          python3 -m zipfile -e terraform.zip terraform/
          .\terraform\terraform.exe --version
          cd src/
          ..\terraform\terraform.exe init
          ..\terraform\terraform.exe apply -auto-approve
