
name: Test Run

on:
  workflow_dispatch:
    inputs:
      destroy:
        default: false

jobs:
  test-run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Check Node Version
        run: |
          node -v
          npm --version
      
      - name: test outputs
        id: step1
        run: echo "exists=OK" >> $GITHUB_OUTPUT
      
      - name: If exists
        if: steps.step1.outputs.exists == 'OK'
        run: echo exists
        
      - name: If not
        if: steps.step1.outputs.exists != 'OK'
        run: echo not exists
      
      - name: Install ibmcloud cli
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud login --apikey ${{ secrets.IBM_API_KEY }} --no-region
          ibmcloud plugin install is
          ibmcloud plugin install cloud-object-storage
      
      - name: Main
        run: |
          echo $INPUT_DESTROY
          if [[ "$INPUT_DESTROY" -eq "false" ]]; then echo false; fi
          cd src
          #python3 main.py
          
          chmod a+x test.sh
          ./test.sh
          echo $?
      
      - name: After Success
        if: success()
        run: |
          echo Success

      - name: After Failure
        if: failure()
        run: |
          echo Failure
