
name: Test Run

on:
  workflow_dispatch:
    inputs:
      destroy:
        default: false

jobs:
  test-run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Check Node Version
        run: |
          node -v
          npm --version
      
      - name: Main
        run: |
          echo destroy = "$INPUT_DESTROY"
          if [[ "$INPUT_DESTROY" -eq "false" ]]; then echo false; fi
          if [[ "$INPUT_DESTROY" -eq "true" ]]; then echo true; fi
          cd src
          #python3 main.py
          
          chmod a+x test.sh
          ./test.sh
          echo $?
      
      - name: After Success
        if: success()
        run: |
          echo Success

      - name: After Failure
        if: failure()
        run: |
          echo Failure
