
name: Test Run

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        default: false

jobs:
  test-run:
    runs-on: ubuntu-latest
    
    env:
      DESTROY: ${{ github.event.inputs.destroy }}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Main
        run: |
          echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          echo env="$GITHUB_ENV"
          echo "color=yellow" >> $GITHUB_ENV
          
      - name: Second
        run: echo color="$color"
      
      - name: After Success
        if: success()
        run: |
          echo Success

      - name: After Failure
        if: failure()
        run: |
          echo Failure
