
name: CI2
on:
  workflow_call:
    secrets:
      some_secret:
        required: true

jobs:
  test-run:
    runs-on: windows-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run Test
        shell: cmd
        run: |
          echo secret = ${{ secrets.some_secret }}
          echo Hello world
