
name: CI2
on: [workflow_dispatch]

jobs:
  test-run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Test
        shell: cmd
        run: |
          pwd
          ls -a
          cd ..
          pwd
          ls -a
