
name: Test

on:
  workflow_dispatch:
    inputs:
      input_1:
        default: "hello"

jobs:
  test-run:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: S1
        if: ${{ github.event.inputs.input_1 }} == "hello"
        run: |
          echo s1
          echo ${{ github.event.inputs.input_1 }}
          
