
name: Test

on:
  workflow_dispatch:

jobs:
  test-run:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Hello
        run: |
          echo ${{ github.steps }}
          echo hello world
