
name: Test

on:
  workflow_dispatch:

jobs:
  test-run:

    strategy:
      matrix:
        repo: [r1, r2, r3]
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Hello
        run: |
          export GITHUB_USER=thakee-kochasoft
          export GITHUB_TOKEN=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
          export GITHUB_REPOSITORY=thakee-client-repos/demoorganisation-demoproject063
          git clone https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          ls -la
