
name: Test

on:
  workflow_dispatch:

env:
  FOO: bar


jobs:
  test-run:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: S1
        run : |
          echo --${ GITHUB_BASE_REF }--
