
name: Test

on:
  workflow_dispatch:

jobs:
  test-run:

    strategy:
      matrix:
        repo: [r1, r2, r3]
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Hello
        run: |
          echo ${{ matrix.repo }}
