
name: Git repo workflow

on:
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
#      - name: Configure Git
#        run: |
#          export MY_GH_PAT=${{ secrets.MY_GH_PAT }}
#          git config --global credential.helper 'store --file ~/.git-credentials'
#          echo "https://${ MY_GH_PAT }:x-oauth-basic@github.com" > ~/.git-credentials

      # If the bucket not exists, it'll clone the bucket repo.
      - name: Checkout The Repo
        uses: actions/checkout@v3
        with:
          repository: thakee-kochasoft/tf-repo-1
          token: ${{ secrets.MY_GH_PAT }}
          path: tf-repo-1

      - name: Configure git
        run: |
          cd tf-repo-1
          git config --global credential.helper 'store --file ~/.git-credentials'
          echo "https://${{ secrets.MY_GH_PAT }}:x-oauth-basic@github.com" > ~/.git-credentials

          echo "helloworld" > hello.txt
          git add .
          git commit -m "hello.txt file added"
          git push

      #- name: Upload source
      #  run: |

      - name: After Success
        if: success()
        run: |
          echo Success

      - name: After Failure
        if: failure()
        run: |
          echo Failure
